//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_Rental_Web.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class carreg
    {
        public int Id { get; set; }
        public string carNo { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string Available { get; set; }
    }
}
